---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: mesosphere.github.io-charts-stable
        namespace: kommander-flux
      version: 2.20.5
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: external-dns
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-2.20.5-d2iq-defaults
  targetNamespace: ${releaseNamespace}
