---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: cert-manager-setup
      sourceRef:
        kind: HelmRepository
        name: mesosphere.github.io-charts-stable
        namespace: kommander-flux
      version: "0.2.7"
  interval: 15s
  install:
    remediation:
      retries: 30
  createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: cert-manager
  targetNamespace: cert-manager
