---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: mesosphere.github.io-charts-stable
        namespace: kommander-flux
      version: 0.12.2
  interval: 15s
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  releaseName: metallb
  valuesFrom:
    - kind: ConfigMap
      name: metallb-0.12.2-d2iq-defaults
  targetNamespace: ${releaseNamespace}
