---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kommander-appmanagement-0.1.0-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    controllerManager:
      containers:
        manager:
          replicas: "${kommanderAppManagementReplicas}"
          image:
            tag: "${appManagementImageTag}"
            repository: "${appManagementImageRepository}"
            pullPolicy: IfNotPresent
