---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mesosphere.github.io-charts-stable
  namespace: kommander-flux
spec:
  interval: 10m
  timeout: 1m
  url: "${helmMirrorURL:=https://mesosphere.github.io/charts/stable}"
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mesosphere.github.io-charts-staging
  namespace: kommander-flux
spec:
  interval: 10m
  timeout: 1m
  url: "${helmMirrorURL:=https://mesosphere.github.io/charts/staging}"
