apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubefed-release
  namespace: ${releaseNamespace}
spec:
  force: false
  prune: true
  interval: 1m0s
  path: ./services/kubefed/0.8.1/release
  sourceRef:
    kind: GitRepository
    name: management
    namespace: kommander-flux
  timeout: 60s
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: substitution-vars
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kubefed
      namespace: ${releaseNamespace}
