---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: project-grafana-logging
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana.github.io
        namespace: kommander-flux
      version: "6.13.9"
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: project-grafana-logging-6.13.9-d2iq-defaults
  targetNamespace: ${releaseNamespace}
