
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns-2.20.5-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |-
    image:
      registry: docker.io
      repository: bitnami/external-dns
      tag: 0.7.0-debian-10-r0
    service:
      labels:
        servicemonitor.kommander.mesosphere.io/path: "metrics"
    metrics:
      enabled: true
